name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # ✅ Manual Foundry installation that always works
      - name: Install Foundry (force 1.4.3-stable)
        shell: bash
        run: |
          set -e
          curl -L https://foundry.paradigm.xyz | bash
          export PATH="$HOME/.foundry/bin:$PATH"
          source "$HOME/.bashrc" || true
          foundryup -v 1.4.3-stable || foundryup -v stable
          forge --version

      - name: Run Forge fmt
        run: |
          export PATH="$HOME/.foundry/bin:$PATH"
          forge fmt --check
        id: fmt

      - name: Run Forge build
        run: |
          export PATH="$HOME/.foundry/bin:$PATH"
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          export PATH="$HOME/.foundry/bin:$PATH"
          forge test -vvv
        id: test
