name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # Force a clean Foundry install with the stable version
      - name: Install Foundry (force stable)
        shell: bash
        run: |
          set -e
          curl -L https://foundry.paradigm.xyz | bash
          export PATH="$PATH:/home/runner/.foundry/bin"
          /home/runner/.foundry/bin/foundryup -v 1.3.5-stable
          /home/runner/.foundry/bin/forge --version

      - name: Run Forge fmt
        run: |
          /home/runner/.foundry/bin/forge fmt --check
        id: fmt

      - name: Run Forge build
        run: |
          /home/runner/.foundry/bin/forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          /home/runner/.foundry/bin/forge test -vvv
        id: test
